import { Router, type IRouter } from "express";
import healthRouter from "./health";
import storageRouter from "./storage";
import dashboardRouter from "./dashboard";
import clientsRouter from "./clients";
import clientTransactionsRouter from "./clientTransactions";
import subcontractorsRouter from "./subcontractors";
import subcontractorTransactionsRouter from "./subcontractorTransactions";
import trucksRouter from "./trucks";
import driversRouter from "./drivers";
import batchesRouter from "./batches";
import tripsRouter from "./trips";
import tripExpensesRouter from "./tripExpenses";
import clearancesRouter from "./clearances";
import invoicesRouter from "./invoices";
import companyExpensesRouter from "./companyExpenses";
import expensesRouter from "./expenses";
import reportsRouter from "./reports";
import uploadsRouter from "./uploads";
import companySettingsRouter from "./companySettings";
import authRouter from "./auth";
import usersRouter from "./users";
import setupRouter from "./setup";
import auditLogsRouter from "./auditLogs";
import truckDriverAssignmentsRouter from "./truckDriverAssignments";
import periodsRouter from "./periods";
import nominationsRouter from "./nominations";
import agentsRouter from "./agents";
import glRouter from "./gl";
import payrollRouter from "./payroll";
import suppliersRouter from "./suppliers";
import pettyCashRouter from "./pettyCash";
import documentsRouter from "./documents";
import bankAccountsRouter from "./bankAccounts";
import tasksRouter from "./tasks";
import notificationsRouter from "./notifications";

const router: IRouter = Router();

router.use(healthRouter);
router.use(storageRouter);
router.use("/dashboard", dashboardRouter);
router.use("/clients", clientsRouter);
router.use("/client-transactions", clientTransactionsRouter);
router.use("/subcontractors", subcontractorsRouter);
router.use("/subcontractor-transactions", subcontractorTransactionsRouter);
router.use("/trucks", trucksRouter);
router.use("/drivers", driversRouter);
router.use("/batches", batchesRouter);
router.use("/trips", tripsRouter);
router.use("/trip-expenses", tripExpensesRouter);
router.use("/clearances", clearancesRouter);
router.use("/invoices", invoicesRouter);
router.use("/company-expenses", companyExpensesRouter);
router.use("/expenses", expensesRouter);
router.use("/reports", reportsRouter);
router.use(uploadsRouter);
router.use("/company-settings", companySettingsRouter);
router.use("/auth", authRouter);
router.use("/users", usersRouter);
router.use("/setup", setupRouter);
router.use("/audit-logs", auditLogsRouter);
router.use("/truck-driver-engagements", truckDriverAssignmentsRouter);
router.use("/truck-driver-engagements-all-current", truckDriverAssignmentsRouter);
router.use("/periods", periodsRouter);
router.use("/nominations", nominationsRouter);
router.use("/agents", agentsRouter);
router.use("/payroll", payrollRouter);
router.use("/gl", glRouter);
router.use("/suppliers", suppliersRouter);
router.use("/petty-cash", pettyCashRouter);
router.use("/documents", documentsRouter);
router.use("/bank-accounts", bankAccountsRouter);
router.use("/tasks", tasksRouter);
router.use("/notifications", notificationsRouter);

export default router;
