import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link, useRoute, useLocation } from "wouter";
import { Layout, PageHeader, PageContent } from "@/components/Layout";
import { formatCurrency, formatDate, cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { ArrowLeft, Building2, Printer } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

type Period = { id: number; name: string; startDate: string; endDate: string; isClosed: boolean };
type TxLine = {
  id: number;
  type: string;
  amount: number;
  reference: string | null;
  batchId: number | null;
  batchName: string | null;
  description: string | null;
  transactionDate: string;
  invoiceId: number | null;
};
type Statement = {
  client: { id: number; name: string; balance: number };
  periodName: string;
  periodId: number | null;
  transactions: TxLine[];
  summary: {
    totalInvoiced: number;
    totalAdvances: number;
    totalPayments: number;
    totalAdjustments: number;
    netBalance: number;
    openingBalance: number;
    closingBalance: number;
  };
};

const TX_LABELS: Record<string, { label: string; sign: 1 | -1; color: string }> = {
  invoice:     { label: "Invoice",      sign: 1,  color: "text-foreground" },
  advance:     { label: "Advance Rcvd", sign: -1, color: "text-green-400" },
  payment:     { label: "Payment Rcvd", sign: -1, color: "text-green-400" },
  adjustment:  { label: "Adjustment",   sign: 1,  color: "text-amber-400" },
};

function StatRow({ label, value, deduct, isSub, isTotal }: {
  label: string; value: number; deduct?: boolean; isSub?: boolean; isTotal?: boolean;
}) {
  return (
    <div className={cn(
      "flex items-center justify-between py-2.5",
      isTotal ? "border-t border-border pt-3 mt-1" : "border-b border-border/50",
      isSub && "pl-4"
    )}>
      <span className={cn("text-sm", isTotal ? "font-bold text-foreground" : isSub ? "text-muted-foreground" : "font-medium text-foreground")}>
        {label}
      </span>
      <span className={cn(
        "text-sm font-mono font-semibold tabular-nums",
        isTotal ? "text-base text-emerald-400" : deduct ? "text-green-400" : "text-foreground"
      )}>
        {deduct ? `− ${formatCurrency(value)}` : formatCurrency(value)}
      </span>
    </div>
  );
}

function ClientStatementPrintDoc({ statement, company, userName }: { statement: Statement; company: any; userName?: string }) {
  const s = statement.summary;
  const companyName = company?.name ?? "Optima Transport LLC";
  const companyAddress = [company?.address, company?.city, company?.country].filter(Boolean).join(", ");
  const companyPhone = company?.phone ?? "";
  const now = new Date();
  const datePrinted = now.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", hour12: true });
  const C = (v: number) => `$${Math.abs(v).toFixed(2)}`;

  let balance = s.openingBalance;
  const rows = statement.transactions.map((tx, i) => {
    const meta = TX_LABELS[tx.type] ?? { label: tx.type, sign: 1 };
    const isIn = meta.sign === 1;
    if (isIn) balance += tx.amount; else balance -= tx.amount;
    const balLabel = balance < 0 ? `${C(Math.abs(balance))} cr` : C(balance);
    const desc = tx.batchName ?? tx.description ?? meta.label;
    return `<tr style="border-bottom:1px solid #f0f0f0;background:${i % 2 === 0 ? "#fff" : "#fafafa"};">
      <td style="padding:5px 10px;white-space:nowrap;color:#444;">${formatDate(tx.transactionDate)}</td>
      <td style="padding:5px 10px;">${desc}</td>
      <td style="padding:5px 10px;color:#666;">${tx.reference ?? "—"}</td>
      <td style="padding:5px 10px;text-align:right;">${isIn ? C(tx.amount) : ""}</td>
      <td style="padding:5px 10px;text-align:right;">${!isIn ? C(tx.amount) : ""}</td>
      <td style="padding:5px 10px;text-align:right;font-weight:600;">${balLabel}</td>
    </tr>`;
  }).join("");

  const finalBal = s.closingBalance;
  const finalStr = finalBal < 0 ? `${C(Math.abs(finalBal))} credit` : `${C(Math.abs(finalBal))} receivable`;

  const html = `<div style="font-family:Arial,sans-serif;color:#111;background:#fff;width:100%;max-width:780px;margin:0 auto;font-size:12px;">
  <div style="text-align:center;padding:20px 16px 14px;border-bottom:2px solid #111;">
    <div style="font-size:22px;font-weight:700;">${companyName}</div>
    ${companyAddress ? `<div style="font-size:10px;color:#666;margin-top:2px;">${companyAddress}${companyPhone ? ` &nbsp;·&nbsp; ${companyPhone}` : ""}</div>` : ""}
    <div style="font-size:12px;color:#444;margin-top:6px;font-weight:600;">Client Account Statement</div>
    <div style="font-size:10px;color:#888;margin-top:3px;">Generated On - ${datePrinted}, ${timeStr}${userName ? `. Generated by - ${userName}` : ""}</div>
  </div>
  <div style="padding:14px 16px 4px;">
    <div style="font-size:17px;font-weight:700;">${statement.client.name}</div>
    <div style="font-size:11px;color:#555;margin-top:3px;">&nbsp;Duration: ${statement.periodName}</div>
  </div>
  <div style="display:grid;grid-template-columns:1fr 1fr 1fr;border:1px solid #ddd;margin:10px 16px 4px;border-radius:3px;overflow:hidden;">
    <div style="padding:12px 16px;text-align:center;border-right:1px solid #ddd;">
      <div style="font-size:10px;text-transform:uppercase;color:#888;margin-bottom:5px;">Total Invoiced</div>
      <div style="font-size:18px;font-weight:700;">${C(s.totalInvoiced)}</div>
    </div>
    <div style="padding:12px 16px;text-align:center;border-right:1px solid #ddd;">
      <div style="font-size:10px;text-transform:uppercase;color:#888;margin-bottom:5px;">Total Received</div>
      <div style="font-size:18px;font-weight:700;">${C(s.totalAdvances + s.totalPayments)}</div>
    </div>
    <div style="padding:12px 16px;text-align:center;">
      <div style="font-size:10px;text-transform:uppercase;color:#888;margin-bottom:5px;">Final Balance</div>
      <div style="font-size:18px;font-weight:700;">${C(Math.abs(finalBal))}</div>
    </div>
  </div>
  <div style="padding:4px 16px 8px;font-size:11px;color:#555;">Total No. of entries: ${statement.transactions.length}</div>
  <table style="width:100%;border-collapse:collapse;font-size:11px;">
    <thead>
      <tr style="border-top:1px solid #ddd;border-bottom:1px solid #ddd;background:#f9f9f9;">
        <th style="padding:7px 10px;text-align:left;font-weight:600;white-space:nowrap;">Date</th>
        <th style="padding:7px 10px;text-align:left;font-weight:600;">Remark</th>
        <th style="padding:7px 10px;text-align:left;font-weight:600;white-space:nowrap;">Reference</th>
        <th style="padding:7px 10px;text-align:right;font-weight:600;white-space:nowrap;">Invoiced</th>
        <th style="padding:7px 10px;text-align:right;font-weight:600;white-space:nowrap;">Received</th>
        <th style="padding:7px 10px;text-align:right;font-weight:600;white-space:nowrap;">Balance</th>
      </tr>
    </thead>
    <tbody>${statement.transactions.length ? rows : `<tr><td colspan="6" style="padding:20px;text-align:center;color:#888;">No transactions for this period.</td></tr>`}</tbody>
    <tfoot>
      <tr style="border-top:2px solid #111;background:#f9f9f9;">
        <td colspan="5" style="padding:7px 10px;font-weight:700;">Final Balance</td>
        <td style="padding:7px 10px;text-align:right;font-weight:700;font-size:13px;">${finalStr}</td>
      </tr>
    </tfoot>
  </table>
  <div style="padding:12px 16px;text-align:center;font-size:10px;color:#888;border-top:1px solid #ddd;margin-top:8px;">Generated by ${companyName}.</div>
</div>`;

  return (
    <div
      id="client-statement-print"
      dangerouslySetInnerHTML={{ __html: html }}
      style={{ position: "fixed", left: "-9999px", top: 0, width: "100%", background: "#fff" }}
    />
  );
}

export default function ClientStatement() {
  const [, params] = useRoute("/clients/:id/statement");
  const [, navigate] = useLocation();
  const clientId = Number(params?.id);
  const [selectedPeriodId, setSelectedPeriodId] = useState<string>("all");
  const { user } = useAuth();

  const { data: periods = [] } = useQuery<Period[]>({
    queryKey: ["/api/periods"],
    queryFn: () => fetch("/api/periods", { credentials: "include" }).then((r) => r.json()),
  });

  const periodParam = selectedPeriodId !== "all" ? `?periodId=${selectedPeriodId}` : "";
  const { data: statement, isLoading } = useQuery<Statement>({
    queryKey: ["/api/clients", clientId, "period-statement", selectedPeriodId],
    queryFn: () =>
      fetch(`/api/clients/${clientId}/period-statement${periodParam}`, { credentials: "include" }).then((r) => r.json()),
    enabled: !!clientId,
  });

  const { data: company } = useQuery({
    queryKey: ["/api/company-settings"],
    queryFn: () => fetch("/api/company-settings", { credentials: "include" }).then((r) => r.json()),
  });

  const handlePrint = () => {
    const prev = document.title;
    document.title = `${statement?.client?.name ?? "Client"} — Account Statement — ${statement?.periodName ?? "All Time"}`;
    window.print();
    document.title = prev;
  };

  if (!clientId) return (
    <Layout>
      <PageContent>
        <div className="text-center py-16 text-muted-foreground">Invalid client link.</div>
      </PageContent>
    </Layout>
  );

  const { summary } = statement ?? {};

  return (
    <Layout>
      <style>{`
        @media print {
          @page { size: A4; margin: 8mm; }
          body * { visibility: hidden !important; }
          #client-statement-print, #client-statement-print * { visibility: visible !important; }
          #client-statement-print {
            display: block !important;
            position: fixed !important;
            left: 0 !important; top: 0 !important;
            width: 100% !important;
            background: #fff !important;
          }
        }
      `}</style>

      <PageHeader
        title={statement?.client?.name ?? "Client Statement"}
        subtitle={`Account Statement — ${statement?.periodName ?? "All Time"}`}
        actions={
          <div className="flex items-center gap-2">
            <Select value={selectedPeriodId} onValueChange={setSelectedPeriodId}>
              <SelectTrigger className="w-44 h-8 text-xs">
                <SelectValue placeholder="Select period" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Time</SelectItem>
                {(periods as Period[]).map((p) => (
                  <SelectItem key={p.id} value={String(p.id)}>{p.name}</SelectItem>
                ))}
              </SelectContent>
            </Select>
            <Button variant="outline" size="sm" onClick={handlePrint} className="gap-1.5" disabled={!statement}>
              <Printer className="w-3.5 h-3.5" />Print
            </Button>
            <Link href={`/clients`}>
              <Button variant="outline" size="sm" className="gap-1.5">
                <ArrowLeft className="w-3.5 h-3.5" />Back
              </Button>
            </Link>
          </div>
        }
      />
      <PageContent>
        {isLoading ? (
          <div className="text-center py-16 text-muted-foreground">Loading statement...</div>
        ) : !statement ? (
          <div className="text-center py-16 text-muted-foreground">Failed to load statement.</div>
        ) : (
          <div className="space-y-6 max-w-5xl mx-auto">
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
              <div className="bg-card border border-border rounded-xl p-4">
                <p className="text-xs text-muted-foreground mb-1">Transactions</p>
                <p className="text-2xl font-bold text-foreground">{statement.transactions.length}</p>
              </div>
              <div className="bg-card border border-border rounded-xl p-4">
                <p className="text-xs text-muted-foreground mb-1">Total Invoiced</p>
                <p className="text-xl font-bold text-foreground">{formatCurrency(summary!.totalInvoiced)}</p>
              </div>
              <div className="bg-card border border-border rounded-xl p-4">
                <p className="text-xs text-muted-foreground mb-1">Opening Balance</p>
                <p className={cn("text-xl font-bold", summary!.openingBalance >= 0 ? "text-foreground" : "text-green-400")}>
                  {formatCurrency(Math.abs(summary!.openingBalance))}
                  <span className="text-xs font-normal ml-1">{summary!.openingBalance >= 0 ? "owed" : "credit"}</span>
                </p>
              </div>
              <div className={cn("rounded-xl p-4 border",
                summary!.closingBalance > 0 ? "bg-red-500/10 border-red-500/20" : "bg-green-500/10 border-green-500/20"
              )}>
                <p className="text-xs text-muted-foreground mb-1">Closing Balance</p>
                <p className={cn("text-xl font-bold", summary!.closingBalance > 0 ? "text-red-400" : "text-green-400")}>
                  {formatCurrency(Math.abs(summary!.closingBalance))}
                  <span className="text-xs font-normal ml-1">{summary!.closingBalance > 0 ? "receivable" : "credit"}</span>
                </p>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              <div className="bg-card border border-border rounded-xl p-5">
                <p className="text-sm font-semibold text-foreground mb-4">Account Summary</p>
                <StatRow label="Total Invoiced" value={summary!.totalInvoiced} />
                {summary!.totalAdjustments !== 0 && (
                  <StatRow label="Adjustments" value={summary!.totalAdjustments} isSub />
                )}
                <StatRow label="Advances Received" value={summary!.totalAdvances} deduct isSub />
                <StatRow label="Payments Received" value={summary!.totalPayments} deduct isSub />
                <StatRow label="Net Balance (Receivable)" value={summary!.netBalance} isTotal />
              </div>

              <div className="bg-card border border-border rounded-xl p-5">
                <p className="text-sm font-semibold text-foreground mb-4">Settlement Summary</p>
                <div className="flex items-center justify-between py-2.5 border-b border-border/50">
                  <span className="text-sm text-muted-foreground">Opening Balance B/F</span>
                  <span className="text-sm font-mono font-semibold">{formatCurrency(summary!.openingBalance)}</span>
                </div>
                <div className="flex items-center justify-between py-2.5 border-b border-border/50">
                  <span className="text-sm text-muted-foreground">Net This Period</span>
                  <span className="text-sm font-mono font-semibold">{formatCurrency(summary!.netBalance)}</span>
                </div>
                <div className="flex items-center justify-between pt-3 mt-1 border-t border-border">
                  <span className="text-sm font-bold text-foreground">Closing Balance</span>
                  <span className={cn(
                    "text-base font-bold font-mono",
                    summary!.closingBalance > 0 ? "text-red-400" : "text-green-400"
                  )}>
                    {formatCurrency(Math.abs(summary!.closingBalance))}
                    <span className="text-xs font-normal ml-1">{summary!.closingBalance > 0 ? "receivable" : "credit"}</span>
                  </span>
                </div>
              </div>
            </div>

            <div className="bg-card border border-border rounded-xl overflow-hidden">
              <div className="px-5 py-4 border-b border-border flex items-center gap-2">
                <Building2 className="w-4 h-4 text-muted-foreground" />
                <h3 className="text-sm font-semibold text-foreground">
                  Transaction Detail — {statement.transactions.length} entries
                </h3>
              </div>
              {statement.transactions.length === 0 ? (
                <div className="text-center py-12 text-muted-foreground">
                  <Building2 className="w-8 h-8 mx-auto mb-2 opacity-30" />
                  <p className="text-sm">No transactions found for this period.</p>
                </div>
              ) : (
                <div className="overflow-x-auto">
                  <table className="w-full text-xs">
                    <thead className="bg-secondary/50">
                      <tr>
                        <th className="px-3 py-3 text-left font-medium text-muted-foreground">Date</th>
                        <th className="px-3 py-3 text-left font-medium text-muted-foreground">Type</th>
                        <th className="px-3 py-3 text-left font-medium text-muted-foreground">Batch / Description</th>
                        <th className="px-3 py-3 text-left font-medium text-muted-foreground">Reference</th>
                        <th className="px-3 py-3 text-right font-medium text-muted-foreground">Debit</th>
                        <th className="px-3 py-3 text-right font-medium text-muted-foreground">Credit</th>
                      </tr>
                    </thead>
                    <tbody className="divide-y divide-border/40">
                      {statement.transactions.map((tx) => {
                        const meta = TX_LABELS[tx.type] ?? { label: tx.type, sign: 1, color: "text-foreground" };
                        const isDebit = meta.sign === 1;
                        const isInvoice = tx.type === "invoice" && tx.invoiceId;
                        return (
                          <tr
                            key={tx.id}
                            className={cn("hover:bg-secondary/30 transition-colors", isInvoice && "cursor-pointer")}
                            onClick={isInvoice ? () => navigate(`/invoices/${tx.invoiceId}`) : undefined}
                          >
                            <td className="px-3 py-2.5 text-muted-foreground whitespace-nowrap">{formatDate(tx.transactionDate)}</td>
                            <td className="px-3 py-2.5">
                              <span className={cn("font-medium", meta.color)}>{meta.label}</span>
                              {isInvoice && <span className="ml-1.5 text-xs text-primary opacity-60">↗</span>}
                            </td>
                            <td className="px-3 py-2.5 text-muted-foreground">
                              {tx.batchName ? (
                                <span className="font-medium text-foreground">{tx.batchName}</span>
                              ) : tx.description ? (
                                <span>{tx.description}</span>
                              ) : <span className="opacity-40">—</span>}
                            </td>
                            <td className="px-3 py-2.5 font-mono text-muted-foreground">{tx.reference ?? <span className="opacity-40">—</span>}</td>
                            <td className="px-3 py-2.5 text-right font-mono">
                              {isDebit ? formatCurrency(tx.amount) : <span className="opacity-30">—</span>}
                            </td>
                            <td className="px-3 py-2.5 text-right font-mono text-green-400">
                              {!isDebit ? formatCurrency(tx.amount) : <span className="opacity-30">—</span>}
                            </td>
                          </tr>
                        );
                      })}
                    </tbody>
                    <tfoot className="border-t-2 border-border bg-secondary/50">
                      <tr>
                        <td colSpan={4} className="px-3 py-3 text-xs font-bold text-foreground">
                          TOTAL ({statement.transactions.length} entries)
                        </td>
                        <td className="px-3 py-3 text-right font-mono font-bold">
                          {formatCurrency(summary!.totalInvoiced + summary!.totalAdjustments)}
                        </td>
                        <td className="px-3 py-3 text-right font-mono font-bold text-green-400">
                          {formatCurrency(summary!.totalAdvances + summary!.totalPayments)}
                        </td>
                      </tr>
                    </tfoot>
                  </table>
                </div>
              )}
            </div>
          </div>
        )}
      </PageContent>

      {statement && <ClientStatementPrintDoc statement={statement} company={company} userName={(user as any)?.name ?? (user as any)?.email} />}
    </Layout>
  );
}
