import { useQuery } from "@tanstack/react-query";
import { useRoute, Link } from "wouter";
import { Layout, PageHeader, PageContent } from "@/components/Layout";
import { formatCurrency, formatDate, cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import { ArrowLeft, Printer } from "lucide-react";
import { useAuth } from "@/contexts/AuthContext";

function generateFleetStatementHtml(data: any, company: any, userName?: string): string {
  const truck = data.truck ?? {};
  const trips: any[] = (data.trips ?? []).filter((t: any) => !["cancelled", "amended_out"].includes(t.status));
  const otherExpenses: any[] = data.otherExpenses ?? [];
  const companyName = company?.name ?? "Optima Transport LLC";
  const companyAddress = [company?.address, company?.city, company?.country].filter(Boolean).join(", ");
  const companyPhone = company?.phone ?? "";
  const now = new Date();
  const datePrinted = now.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-GB", { hour: "2-digit", minute: "2-digit", hour12: true });
  const C = (v: number) => `$${Math.abs(v).toFixed(2)}`;

  type Entry = { date: string; remark: string; mode: string; cashIn: number; cashOut: number };
  const rawEntries: Entry[] = [
    ...trips.map((t: any) => ({
      date: t.createdAt,
      remark: `${t.batchName ?? "—"} (${t.product ?? "—"})`,
      mode: "Trip",
      cashIn: t.grossRevenue ?? 0,
      cashOut: (t.commission ?? 0) + (t.tripExpenses ?? 0),
    })),
    ...otherExpenses.map((e: any) => ({
      date: e.expenseDate ?? e.createdAt,
      remark: (e.description ?? e.costType ?? "Expense").replace(/_/g, " "),
      mode: "Cash",
      cashIn: 0,
      cashOut: parseFloat(e.amount ?? 0),
    })),
  ].sort((a, b) => new Date(a.date).getTime() - new Date(b.date).getTime());

  const totalIn = rawEntries.reduce((s, e) => s + e.cashIn, 0);
  const totalOut = rawEntries.reduce((s, e) => s + e.cashOut, 0);
  let balance = 0;

  const rows = rawEntries.map((e, i) => {
    balance += e.cashIn - e.cashOut;
    const balLabel = balance < 0 ? `(${C(Math.abs(balance))})` : C(balance);
    return `<tr style="border-bottom:1px solid #f0f0f0;background:${i % 2 === 0 ? "#fff" : "#fafafa"};">
      <td style="padding:5px 10px;white-space:nowrap;color:#444;">${formatDate(e.date)}</td>
      <td style="padding:5px 10px;">${e.remark}</td>
      <td style="padding:5px 10px;color:#666;">${e.mode}</td>
      <td style="padding:5px 10px;text-align:right;">${e.cashIn > 0 ? C(e.cashIn) : ""}</td>
      <td style="padding:5px 10px;text-align:right;">${e.cashOut > 0 ? C(e.cashOut) : ""}</td>
      <td style="padding:5px 10px;text-align:right;font-weight:600;">${balLabel}</td>
    </tr>`;
  }).join("");

  const finalStr = balance < 0 ? `(${C(Math.abs(balance))}) deficit` : `${C(balance)} net`;
  const truckLabel = [truck.plateNumber, truck.trailerPlate].filter(Boolean).join(" / ");

  return `<div style="font-family:Arial,sans-serif;color:#111;background:#fff;width:100%;max-width:780px;margin:0 auto;font-size:12px;">
  <div style="text-align:center;padding:20px 16px 14px;border-bottom:2px solid #111;">
    <div style="font-size:22px;font-weight:700;">${companyName}</div>
    ${companyAddress ? `<div style="font-size:10px;color:#666;margin-top:2px;">${companyAddress}${companyPhone ? ` &nbsp;·&nbsp; ${companyPhone}` : ""}</div>` : ""}
    <div style="font-size:12px;color:#444;margin-top:6px;font-weight:600;">Fleet Cash Statement</div>
    <div style="font-size:10px;color:#888;margin-top:3px;">Generated On - ${datePrinted}, ${timeStr}${userName ? `. Generated by - ${userName}` : ""}</div>
  </div>
  <div style="padding:14px 16px 4px;">
    <div style="font-size:17px;font-weight:700;">${truckLabel}</div>
    <div style="font-size:11px;color:#555;margin-top:3px;">&nbsp;${[truck.subcontractorName].filter(Boolean).join(" · ") || "Company Owned"} · ${trips.length} active trips</div>
  </div>
  <div style="display:grid;grid-template-columns:1fr 1fr 1fr;border:1px solid #ddd;margin:10px 16px 4px;border-radius:3px;overflow:hidden;">
    <div style="padding:12px 16px;text-align:center;border-right:1px solid #ddd;">
      <div style="font-size:10px;text-transform:uppercase;color:#888;margin-bottom:5px;">Total Revenue</div>
      <div style="font-size:18px;font-weight:700;">${C(totalIn)}</div>
    </div>
    <div style="padding:12px 16px;text-align:center;border-right:1px solid #ddd;">
      <div style="font-size:10px;text-transform:uppercase;color:#888;margin-bottom:5px;">Total Costs</div>
      <div style="font-size:18px;font-weight:700;">${C(totalOut)}</div>
    </div>
    <div style="padding:12px 16px;text-align:center;">
      <div style="font-size:10px;text-transform:uppercase;color:#888;margin-bottom:5px;">Net Profit</div>
      <div style="font-size:18px;font-weight:700;">${C(Math.abs(balance))}</div>
    </div>
  </div>
  <div style="padding:4px 16px 8px;font-size:11px;color:#555;">Total No. of entries: ${rawEntries.length}</div>
  <table style="width:100%;border-collapse:collapse;font-size:11px;">
    <thead>
      <tr style="border-top:1px solid #ddd;border-bottom:1px solid #ddd;background:#f9f9f9;">
        <th style="padding:7px 10px;text-align:left;font-weight:600;white-space:nowrap;">Date</th>
        <th style="padding:7px 10px;text-align:left;font-weight:600;">Remark</th>
        <th style="padding:7px 10px;text-align:left;font-weight:600;white-space:nowrap;">Mode</th>
        <th style="padding:7px 10px;text-align:right;font-weight:600;white-space:nowrap;">Revenue</th>
        <th style="padding:7px 10px;text-align:right;font-weight:600;white-space:nowrap;">Costs</th>
        <th style="padding:7px 10px;text-align:right;font-weight:600;white-space:nowrap;">Balance</th>
      </tr>
    </thead>
    <tbody>${rawEntries.length ? rows : `<tr><td colspan="6" style="padding:20px;text-align:center;color:#888;">No entries recorded.</td></tr>`}</tbody>
    <tfoot>
      <tr style="border-top:2px solid #111;background:#f9f9f9;">
        <td colspan="5" style="padding:7px 10px;font-weight:700;">Final Balance</td>
        <td style="padding:7px 10px;text-align:right;font-weight:700;font-size:13px;">${finalStr}</td>
      </tr>
    </tfoot>
  </table>
  <div style="padding:12px 16px;text-align:center;font-size:10px;color:#888;border-top:1px solid #ddd;margin-top:8px;">Generated by ${companyName}.</div>
</div>`;
}

export default function FleetStatement() {
  const [, params] = useRoute("/fleet/:id/statement");
  const truckId = Number(params?.id);
  const { user } = useAuth();

  const { data, isLoading } = useQuery<any>({
    queryKey: [`/api/trucks/${truckId}/detail`],
    queryFn: () => fetch(`/api/trucks/${truckId}/detail`, { credentials: "include" }).then((r) => r.json()),
    enabled: !!truckId,
  });

  const { data: company } = useQuery<any>({
    queryKey: ["/api/company-settings"],
    queryFn: () => fetch("/api/company-settings", { credentials: "include" }).then((r) => r.json()),
  });

  const truck = data?.truck;
  const summary = data?.summary;
  const trips: any[] = (data?.trips ?? []).filter((t: any) => !["cancelled", "amended_out"].includes(t.status));

  const handlePrint = () => {
    if (!data) return;
    const w = window.open("", "_blank");
    if (!w) return;
    const html = generateFleetStatementHtml(data, company, (user as any)?.name ?? (user as any)?.email);
    const title = `${truck?.plateNumber ?? "Truck"} — Fleet Statement`;
    w.document.write(`<!DOCTYPE html><html><head><title>${title}</title><style>*{box-sizing:border-box;}body{margin:0;padding:0;background:#fff;}@media print{@page{size:A4;margin:8mm;}}</style></head><body>${html}</body></html>`);
    w.document.close();
    w.focus();
    setTimeout(() => { try { w.print(); } catch (_) {} }, 350);
  };

  return (
    <Layout>
      <PageHeader
        title={truck ? `${truck.plateNumber} — Fleet Statement` : "Fleet Statement"}
        subtitle={truck?.subcontractorName ? `Subcontractor: ${truck.subcontractorName}` : "Company Owned"}
        actions={
          <div className="flex items-center gap-2">
            <Button variant="outline" size="sm" onClick={handlePrint} disabled={!data} className="gap-1.5">
              <Printer className="w-3.5 h-3.5" />Print Statement
            </Button>
            <Link href={`/fleet/${truckId}`}>
              <Button variant="outline" size="sm" className="gap-1.5">
                <ArrowLeft className="w-3.5 h-3.5" />Back to Truck
              </Button>
            </Link>
          </div>
        }
      />
      <PageContent>
        {isLoading ? (
          <div className="text-center py-16 text-muted-foreground">Loading fleet statement...</div>
        ) : !data ? (
          <div className="text-center py-16 text-muted-foreground">Failed to load truck data.</div>
        ) : (
          <div className="space-y-6 max-w-5xl mx-auto">
            {/* Summary KPIs */}
            <div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-6 gap-3">
              {[
                { label: "Active Trips", value: String(summary?.totalTrips ?? 0), mono: false },
                { label: "Total Revenue", value: formatCurrency(summary?.totalRevenue ?? 0), mono: true },
                { label: "Commission", value: formatCurrency(summary?.totalCommission ?? 0), mono: true, red: true },
                { label: "Trip Expenses", value: formatCurrency(summary?.totalTripExpenses ?? 0), mono: true, red: true },
                { label: "Other Expenses", value: formatCurrency(summary?.totalOtherExpenses ?? 0), mono: true, red: true },
                { label: "Net Profit", value: formatCurrency(summary?.netProfit ?? 0), mono: true, green: true },
              ].map((k) => (
                <div key={k.label} className="bg-card border border-border rounded-xl p-4">
                  <p className="text-xs text-muted-foreground mb-1">{k.label}</p>
                  <p className={cn("text-lg font-bold", k.red ? "text-red-400" : k.green ? "text-emerald-400" : "text-foreground", k.mono && "font-mono")}>{k.value}</p>
                </div>
              ))}
            </div>

            {/* Trip cashbook table */}
            <div className="bg-card border border-border rounded-xl overflow-hidden">
              <div className="px-5 py-4 border-b border-border">
                <h3 className="text-sm font-semibold text-foreground">Cash Statement — {trips.length} trips + {data?.otherExpenses?.length ?? 0} other expenses</h3>
              </div>
              <div className="overflow-x-auto">
                <table className="w-full text-xs">
                  <thead className="bg-secondary/50">
                    <tr>
                      <th className="px-3 py-3 text-left font-medium text-muted-foreground whitespace-nowrap">Date</th>
                      <th className="px-3 py-3 text-left font-medium text-muted-foreground">Batch / Remark</th>
                      <th className="px-3 py-3 text-left font-medium text-muted-foreground">Mode</th>
                      <th className="px-3 py-3 text-right font-medium text-muted-foreground">Revenue</th>
                      <th className="px-3 py-3 text-right font-medium text-red-400">Costs</th>
                      <th className="px-3 py-3 text-right font-medium text-foreground">Balance</th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-border/40">
                    {(() => {
                      let runBal = 0;
                      const allEntries = [
                        ...trips.map((t: any) => ({
                          date: t.createdAt, remark: `${t.batchName ?? "—"} (${t.product ?? "—"})`,
                          mode: "Trip", cashIn: t.grossRevenue ?? 0, cashOut: (t.commission ?? 0) + (t.tripExpenses ?? 0),
                        })),
                        ...(data?.otherExpenses ?? []).map((e: any) => ({
                          date: e.expenseDate ?? e.createdAt,
                          remark: (e.description ?? e.costType ?? "Expense").replace(/_/g, " "),
                          mode: "Cash", cashIn: 0, cashOut: parseFloat(e.amount ?? 0),
                        })),
                      ].sort((a: any, b: any) => new Date(a.date).getTime() - new Date(b.date).getTime());

                      if (!allEntries.length) return (
                        <tr><td colSpan={6} className="px-4 py-10 text-center text-muted-foreground">No entries recorded.</td></tr>
                      );

                      return allEntries.map((e: any, i: number) => {
                        runBal += e.cashIn - e.cashOut;
                        return (
                          <tr key={i} className="hover:bg-secondary/20">
                            <td className="px-3 py-2 whitespace-nowrap text-muted-foreground">{formatDate(e.date)}</td>
                            <td className="px-3 py-2">{e.remark}</td>
                            <td className="px-3 py-2 text-muted-foreground">{e.mode}</td>
                            <td className="px-3 py-2 text-right font-mono">{e.cashIn > 0 ? formatCurrency(e.cashIn) : <span className="opacity-30">—</span>}</td>
                            <td className="px-3 py-2 text-right font-mono text-red-400">{e.cashOut > 0 ? formatCurrency(e.cashOut) : <span className="opacity-30">—</span>}</td>
                            <td className={cn("px-3 py-2 text-right font-mono font-bold", runBal < 0 ? "text-red-400" : "text-emerald-400")}>{formatCurrency(runBal)}</td>
                          </tr>
                        );
                      });
                    })()}
                  </tbody>
                  <tfoot className="border-t-2 border-border bg-secondary/50">
                    <tr>
                      <td colSpan={3} className="px-3 py-3 text-xs font-bold text-foreground">TOTAL</td>
                      <td className="px-3 py-3 text-right font-mono font-bold">{formatCurrency(summary?.totalRevenue ?? 0)}</td>
                      <td className="px-3 py-3 text-right font-mono font-bold text-red-400">{formatCurrency((summary?.totalCommission ?? 0) + (summary?.totalTripExpenses ?? 0) + (summary?.totalOtherExpenses ?? 0))}</td>
                      <td className={cn("px-3 py-3 text-right font-mono font-bold", (summary?.netProfit ?? 0) < 0 ? "text-red-400" : "text-emerald-400")}>{formatCurrency(summary?.netProfit ?? 0)}</td>
                    </tr>
                  </tfoot>
                </table>
              </div>
            </div>
          </div>
        )}
      </PageContent>
    </Layout>
  );
}
